#10 feat: Member Entity, Service, Repository 추가
dnd-side-project/dnd-11th-4-backend pull request #13
Opened 2024-08-14 14:53 UTC by min-0

## What is this PR? :mag:
회원 엔티티, 서비스, 레포지토리 로직 추가

## Changes :memo:
- jwt 의존성 추가
- 회원 entity 생성
- 회원 정보 저장하는 service 생성
- 회원 repository 생성

2024-08-14 16:19 UTC, youngreal requested changes
고생하셨습니다

2024-08-14 16:19 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> +@NoArgsConstructor
아래의 코드는 어떠신가요? @AllArgsConstructor도 좋지만 외부에서 new()로 자유롭게 객체를 생성하는걸 막지못할것같아요. 이미 만들어주신 factory method가 있으니 private 생성자로 변경해 객체 생성과정을 캡슐화 할 수 있습니다.

```java
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@Entity
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String email;
    
    @Builder
    private Member(String name, String email) {
          this.name = name;
          this.email = email;
    }
    
    public static Member of(String name, String email){
        return Member.builder()
                .name(name)
                .email(email)
                .build();
   }
}
```

2024-08-14 16:19 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/member/service/MemberService.java
> +@Transactional(readOnly = true)
이 클래스는 왜 @Transactional이 2개인가요?

2024-08-16 07:49 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/member/service/MemberService.java
> +@Transactional(readOnly = true)
헉 실수인가봐요 ...!ㅎ

2024-08-16 07:49 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> +                .build();
넵! 수정하겠습니당

2024-08-16 07:50 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> +@NoArgsConstructor
좋네요! 반영하겠습니다 ㅎ

2024-08-16 07:58 UTC, youngreal approved these changes
굿

2024-08-16 08:02 UTC, merged