기록하기 API
dnd-side-project/dnd-11th-4-backend pull request #22
Opened 2024-08-26 06:15 UTC by youngreal

## What is this PR? :mag:
방문기록 저장 API 구현

2024-08-26 16:27 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> -    @Column(nullable = false)
이름이 null이어도 되나용 ?!

2024-08-26 16:31 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> -    @Column(nullable = false)
이름은 null이어도 되고 심지어 지금은 아예 필요가 없습니다 닉네임을 쓸거라서요

2024-08-26 16:42 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/controller/request/validation/RegionEnum.java
이 클래스는 코드들이 뭔가 신기하게 생겼어요

2024-08-26 16:45 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/dto/RecordDto.java
> + */
옹 이친구들은 지워도 좋을 거 같애용 혹시 뭐 적으려다가 깜빡하셨나영

2024-08-26 16:49 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/map/controller/request/validation/RegionEnum.java
클라한테 지역을 입력받는데 얘네말고 다른값들이 들어오는걸 방지하기위함입니다 Enum한번 보심 될것같아유

2024-08-26 16:51 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/controller/request/RecordRequest.java
> +	@Size(max = 50, message = "명소 이름은 50자 이내여야 합니다.")
프로토타입에는 명소명 20자로 되어 있어요!

2024-08-26 16:52 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/service/MapService.java
이미지 세장까지 업로드 가능하게 해야하는데, 그 제한이 어디에 있나요 !?
혹시나 있다면 제가 못찾는 거 같아요 알려주세요 !!!!

2024-08-26 16:55 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/domain/MemberRegion.java
> +			.visitCount(1)
visitCount을 지우신 이유가 있나용

2024-08-26 16:57 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/map/service/MapService.java
오 추가하지 않았었는데 검증이 필요해보이네요

2024-08-26 16:58 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/map/domain/MemberRegion.java
> +			.visitCount(1)
MemberRegion 객체는 특정 지역에 방문했을때 최초로 생성이되고, 이후에는 visitCount가 add되는 형태라서 이 객체를 생성했을땐 1번 방문했다는거고, 임의의 visitCount를 받아 생성할 일은 없다고 판단했어요

2024-08-26 17:00 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/map/controller/request/RecordRequest.java
> +	LocalDate localDate
이거 포맷 프로토타입에서 기록할 때 날짜 형식은 2024년7월21일로 되어 있고, 기록 확인할 때는 24.07.21 되어 있네용 ?!
이거에 관련해서 클라이언트 분들이랑 얘기했던 거 같은데 결론이 기억 안나네요 ,,?ㅎ

2024-08-26 17:00 UTC, min-0 requested changes
너ㅓㅓㅓㅓ무 고생하셨네요 !!!!!

2024-08-26 17:01 UTC, min-0 commented on src/main/java/com/dnd/dndtravel/member/domain/Member.java
> -    @Column(nullable = false)
아하 맞다 랜덤 닉네임

2024-08-27 02:07 UTC, youngreal commented on src/main/java/com/dnd/dndtravel/map/controller/request/RecordRequest.java
> +	LocalDate localDate
클라에서 포맷팅 해줄겁니다

2024-08-27 05:05 UTC, merged